# Generated by Django 4.1.3 on 2022-12-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glumac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glumac_ime', models.CharField(max_length=50)),
                ('glumac_prezime', models.CharField(max_length=50)),
                ('glumac_datum_rodenja', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoblje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osoblje_ime', models.CharField(max_length=50)),
                ('osoblje_prezime', models.CharField(max_length=50)),
                ('osoblje_uloga', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Redatelj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redatelj_ime', models.CharField(max_length=50)),
                ('redatelj_prezime', models.CharField(max_length=50)),
                ('redatelj_datum_rodenja', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reklama_izdavac', models.CharField(max_length=50)),
                ('reklama_trajanje', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_ime', models.CharField(max_length=50)),
                ('datum_osnivanja', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Serija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serija_ime', models.CharField(max_length=100)),
                ('serija_datum_objave', models.DateField(blank=True, null=True)),
                ('serija_zanr', models.CharField(max_length=30)),
                ('serija_ocjena', models.IntegerField(default=1)),
                ('serija_budzet', models.IntegerField(default=1)),
                ('serija_drzava_proizvodnje', models.CharField(max_length=50)),
                ('glumac', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.glumac')),
                ('osoblje', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.osoblje')),
                ('redatelj', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.redatelj')),
                ('reklama', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.reklama')),
                ('studio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_ime', models.CharField(max_length=100)),
                ('film_datum_objave', models.DateField(blank=True, null=True)),
                ('film_zanr', models.CharField(max_length=30)),
                ('film_ocjena', models.IntegerField(default=1)),
                ('film_budzet', models.IntegerField(default=1)),
                ('film_drzava_proizvodnje', models.CharField(max_length=50)),
                ('glumac', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.glumac')),
                ('osoblje', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.osoblje')),
                ('redatelj', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.redatelj')),
                ('reklama', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.reklama')),
                ('studio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.studio')),
            ],
        ),
    ]
