# Generated by Django 4.1.3 on 2022-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='glumac',
        ),
        migrations.RemoveField(
            model_name='film',
            name='osoblje',
        ),
        migrations.RemoveField(
            model_name='serija',
            name='glumac',
        ),
        migrations.RemoveField(
            model_name='serija',
            name='osoblje',
        ),
        migrations.AddField(
            model_name='film',
            name='glumac',
            field=models.ManyToManyField(to='main.glumac'),
        ),
        migrations.AddField(
            model_name='film',
            name='osoblje',
            field=models.ManyToManyField(to='main.osoblje'),
        ),
        migrations.AddField(
            model_name='serija',
            name='glumac',
            field=models.ManyToManyField(to='main.glumac'),
        ),
        migrations.AddField(
            model_name='serija',
            name='osoblje',
            field=models.ManyToManyField(to='main.osoblje'),
        ),
    ]
